name: dotnet action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '8.x', '9.x', '10.x' ]
    steps:
    - uses: actions/checkout@v5
    - name: Setup dotnet 5.0
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '5.0.x'
    - name: Setup dotnet ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore tools
      run: dotnet tool restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet execute build
    - name: Test
      run: dotnet execute test
    - name: Test coverage
      run: dotnet execute test:coverage
    - name: Test mutation
      run: dotnet execute test:mutation