name: dotnet action

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '8.x', '9.x', '10.x' ]
    steps:
    - name: Get source code
      uses: actions/checkout@v5
    - name: Setup dotnet ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore tools
      run: dotnet tool restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet r build
    - name: Test
      run: dotnet r test
    - name: Test coverage
      run: dotnet r test:coverage
    - name: Badge
      if: ${{ ( github.ref == format('refs/heads/{0}', github.event.repository.default_branch) ) && ( matrix.dotnet == '8.x' ) }}
      uses: gaelgirodon/ci-badges-action@v1
      with:
        gist-id: 2edc636fc2ff6aff4b056d455f3290be
        token: ${{ secrets.GIST_TOKEN }}